"""Default thermocouple dashboard configuration values."""

DEVICE_NAME = "MCC E-TC-001"
DEFAULT_FURNACE_NUMBER = 1
DEVICE_IP = "169.254.69.179"

DEFAULT_SETPOINT = 200.0
DEFAULT_LOWER_BOUND = 70.0
DEFAULT_UPPER_BOUND = 300.0
DEFAULT_Y_MIN = 100
DEFAULT_Y_MAX = 2000

DEFAULT_SAMPLING_FREQUENCY = 5
GRAPH_WINDOW_SECONDS = 300

DEFAULT_OUTPUT_DIRECTORY = "./recordings"
#LABVIEW_OUTPUT_CHANNELS = 3

#POLLING_INTERVAL = 1000
GRAPH_HEIGHT = 400

CHANNEL_COLORS = {
    1: "#1f77b4",
    2: "#d62728",
    3: "#ff00ff",
}

SETPOINT_COLOR = "red"
LOWER_BOUND_COLOR = "orange"
UPPER_BOUND_COLOR = "purple"
